project_id = "wzbmanfxlpjnrivbezib"

[functions.fetch-html]
verify_jwt = true

[functions.generate-schema]
verify_jwt = true
static_files = [
  "./functions/generate-schema/rules/global.md",
  "./functions/generate-schema/rules/estate.md",
  "./functions/generate-schema/rules/governance.md",
  "./functions/generate-schema/rules/community.md",
  "./functions/generate-schema/rules/siteHomePage.md"
]

[functions.generate-schema-story]
verify_jwt = true

[functions.export-wikidata-beers]
verify_jwt = true

[functions.graph-beers]
verify_jwt = true

[functions.wizmode-process]
verify_jwt = true

[functions.graph-pages]
verify_jwt = true
